version: '3'

services:
  db:
    image: mysql:8
    container_name: hoa-mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes: 
      - hoa-dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - hoa-app-network

  wordpress:
    depends_on: 
      - db
    image: wordpress:5-php7.1-fpm-alpine
    container_name: hoa-wordpress
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - hoa-wordpress:/var/www/html
    networks:
      - hoa-app-network
  
  nginx:
    depends_on:
      - wordpress
    image: nginx:1.16-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - hoa-wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - hoa-app-network

volumes:
  hoa-wordpress:
  hoa-dbdata:

networks:
  hoa-app-network:
    driver: bridge  